# ConfigMap: Stores the Python script that makes HTTP requests
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-client-script
data:
  client.py: |
    # Python client that continuously requests the echo-server service
    import requests
    import time
    import os

    # Get the service URL from environment variable
    service_url = os.getenv("SERVICE_URL", "http://echo-server-svc")
    
    print(f"Python client starting. Will request {service_url}")
    
    # Infinite loop to continuously make requests every 5 seconds
    while True:
        try:
            # Make HTTP GET request to the service
            response = requests.get(service_url, timeout=5)
            print(f"Status: {response.status_code}, Response: {response.text[:200]}")
        except Exception as e:
            print(f"Error: {e}")
        
        # Wait 5 seconds before next request
        time.sleep(5)

---
# Deployment: Creates a pod running the Python client
# Purpose: Tests inter-service connectivity by continuously requesting echo-server-svc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-client-deploy
  labels:
    app: python-client
spec:
  replicas: 1  # Run one instance of the client
  selector:
    matchLabels:
      app: python-client
  template:
    metadata:
      labels:
        app: python-client
    spec:
      containers:
      - name: python-client
        image: python:3.11-slim  # Lightweight Python image
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Install requests library and run the client script
            pip install requests && python /app/client.py
        env:
        - name: SERVICE_URL
          value: "http://echo-server-svc"  # Target service to request
        volumeMounts:
        - name: script
          mountPath: /app  # Mount the ConfigMap script here
      volumes:
      - name: script
        configMap:
          name: python-client-script  # Reference to the ConfigMap above
