# 1. Deployment: Crea el Pod con el servidor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deploy
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        # ¡IMAGEN CORREGIDA! Usamos la imagen oficial de NGINX, que es moderna y ligera.
        image: nginx:latest
        ports:
        - containerPort: 80

---
# 2. Service: Expone el Deployment dentro del clúster
apiVersion: v1
kind: Service
metadata:
  name: echo-server-svc
spec:
  selector:
    app: echo-server
  ports:
  - port: 80
    targetPort: 80 # Puerto del contenedor
  type: ClusterIP